Qiaolei/refactor (#7)
* feat: add modules for springboot discovery

diff --git a/.github/workflows/discovery.yml b/.github/workflows/discovery.yml
--- a/.github/workflows/discovery.yml
+++ b/.github/workflows/discovery.yml
@@ -15,20 +15,64 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
+      with:
+        ref: ${{ github.head_ref }}   # checkout the correct branch name
+        fetch-depth: 0                # fetch the whole repo history
 
     - name: Set up Go
-      uses: actions/setup-go@v3
+      uses: actions/setup-go@v4
       with:
-        go-version: 1.18
+        go-version: '1.20'
 
     - name: Install Dependencies
-      run: sudo apt install go-bindata mingw-w64
-      
+      run: |
+        go install github.com/axw/gocov/gocov@latest
+        go install github.com/AlekSi/gocov-xml@latest
+
+    - name: Test
+      run: |
+        make test
+
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: 'test_report.xml'
+
+    - name: Generate Code Coverage
+      run: |
+        gocov convert coverage.out > coverage.json
+        gocov-xml < coverage.json > coverage.xml
+
+    - name: Publish Code Coverage Report
+      uses: irongut/CodeCoverageSummary@v1.3.0
+      with:
+        filename: coverage.xml
+        badge: true
+        fail_below_min: true
+        format: markdown
+        hide_branch_rate: false
+        hide_complexity: true
+        indicators: true
+        output: both
+        thresholds: '70 80'
+
+    - name: Add Coverage PR Comment
+      uses: marocchino/sticky-pull-request-comment@v2
+      if: github.event_name == 'pull_request'
+      with:
+        recreate: true
+        path: code-coverage-results.md
+
     - name: Build
-      run: chmod +x buildall.sh && ./buildall.sh
-    
+      run: make build
+
     - name: Upload artifacts
       uses: actions/upload-artifact@master
       with:
         name: buildFiles
         path: bin
+
+    - name: Push Coverage Badge
+      run: |
+        .github/workflows/badge.sh
