feat: add modules for springboot discovery

diff --git a/.github/workflows/discovery.yml b/.github/workflows/discovery.yml
--- a/.github/workflows/discovery.yml
+++ b/.github/workflows/discovery.yml
@@ -33,6 +33,12 @@ jobs:
       run: |
         make test
 
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: 'test_report.xml'
+
     - name: Generate Code Coverage
       run: |
         gocov convert coverage.out > coverage.json
